### ISSUE TITLE
make things easier for beginners

### ISSUE THREAD

**Issue by guiseek** [Ammyy9908/js-pool#17]
sorry if I sound nosy, but reading the README, I understood that the idea would be to pass on a little bit about JS in a basic way, right?

in the example about network > axios, wouldn't something like this be better?

```js
const API_URL = 'https://api.github.com/repos/javascript-tutorial/en.javascript.info/commits'

axios.get(API_URL).then(({ data, headers }) => {
  console.log(data);
  console.log(headers);
});
```

so maybe there could be another file demonstrating the use of immediate functions, what do you think?

**Comment by Ammyy9908** [comment]
wait i will check.

**Comment by Ammyy9908** [comment]
Yeah, I checked it, if you have a better option add it to the repo.
